services:
  translation-ms:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - ../.env
    environment:
      # Override database URL to use host.docker.internal for Docker
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5432/corems
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - corems-network

networks:
  corems-network:
    external: true
